apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhooq-spring-boot
  template:
    metadata:
      labels:
        app: jhooq-spring-boot
    spec:
      containers:
        - name: springboot
          image: dwarak1262/jhooq-spring-boot:jhooq-spring-boot
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-spring-boot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq-spring-boot
